apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapp-rc
spec:
   replicas: 3
   selector: 
     app: myonlineapp
   template:
     metadata:
       labels:
          app: myonlineapp
     spec:
        containers:
        - name: myonlineapp-container   
          image: myonlineapp:1
          ports:
          - containerPort: 8080  