apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins-rc
spec:
   replicas: 3
   selector: 
     app: myjenkins
   template:
     metadata:
       labels:
          app: myjenkins
     spec:
        containers:
        - name: myjenkins-container   
          image: swami4iac/myjenkins:1
          ports:
          - containerPort: 8080  